# Generated by Django 4.1.7 on 2023-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestrator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runtime",
            name="max_nmodules",
            field=models.IntegerField(default=0),
        ),
    ]
